# generated by proto/scripts/generate_contracts.py
from __future__ import annotations

from datetime import datetime
from typing import Any, Literal
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field


class ContractModel(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

class HeartbeatActiveLanesItem(ContractModel):
    lane: str = Field(...)
    run_id: UUID | None = Field(default=None, alias="runId")
    dut_id: str | None = Field(default=None, alias="dutId")
    status: Literal['queued', 'running', 'blocked'] = Field(...)
    current_stage: str | None = Field(default=None, alias="currentStage")
    waiting_reason: str | None = Field(default=None, alias="waitingReason")

class LogBatchEntriesItem(ContractModel):
    t: datetime = Field(...)
    lvl: Literal['debug', 'info', 'warn', 'warning', 'error'] = Field(...)
    msg: str = Field(...)

class TestResultStagesItem(ContractModel):
    name: str = Field(...)
    outcome: Literal['passed', 'failed', 'aborted', 'error'] = Field(...)
    started_at: datetime = Field(alias="startedAt")
    finished_at: datetime = Field(alias="finishedAt")

class Heartbeat(ContractModel):
    ts: datetime = Field(...)
    status: Literal['idle', 'running', 'error'] = Field(...)
    current_run_id: UUID | None = Field(default=None, alias="currentRunId")
    active_lanes: list[HeartbeatActiveLanesItem] = Field(alias="activeLanes")

class LogBatch(ContractModel):
    ts: datetime = Field(...)
    run_id: UUID | None = Field(default=None, alias="runId")
    lane: str = Field(...)
    entries: list[LogBatchEntriesItem] = Field(...)

class RunObservation(ContractModel):
    id: UUID = Field(...)
    key: str = Field(...)
    value: str = Field(...)
    stage_index: int = Field(alias="stageIndex")
    stage_name: str = Field(alias="stageName")
    sequence: int = Field(...)
    observed_at: datetime = Field(alias="observedAt")
    verified: bool = Field(...)
    subtest: str | None = Field(default=None, alias="subtest")

class TestResult(ContractModel):
    delivery_id: UUID | None = Field(default=None, alias="deliveryId")
    capture_issues: list[str] | None = Field(default=None, alias="captureIssues")
    observations: list[RunObservation] | None = Field(default=None, alias="observations")
    ts: datetime = Field(...)
    run_id: UUID | None = Field(default=None, alias="runId")
    lane: str = Field(...)
    dut_id: str = Field(alias="dutId")
    outcome: Literal['passed', 'failed', 'aborted', 'error'] = Field(...)
    config_revision: int | None = Field(default=None, alias="configRevision")
    started_at: datetime = Field(alias="startedAt")
    finished_at: datetime = Field(alias="finishedAt")
    stages: list[TestResultStagesItem] | None = Field(default=None, alias="stages")

class Stage(ContractModel):
    delivery_id: UUID | None = Field(default=None, alias="deliveryId")
    capture_issues: list[str] | None = Field(default=None, alias="captureIssues")
    observations: list[RunObservation] | None = Field(default=None, alias="observations")
    dut_id: str | None = Field(default=None, alias="dutId")
    config_revision: int | None = Field(default=None, alias="configRevision")
    ts: datetime = Field(...)
    run_id: UUID | None = Field(default=None, alias="runId")
    lane: str = Field(...)
    index: int = Field(...)
    name: str = Field(...)
    status: Literal['pending', 'blocked', 'running', 'passed', 'failed', 'aborted', 'error'] = Field(...)

class Command(ContractModel):
    id: UUID = Field(...)
    kind: Literal['run-plan', 'run-batch', 'abort-run', 'reboot', 'ack-report'] = Field(...)
    payload: dict[str, Any] | None = Field(default=None, alias="payload")
