# generated by proto/scripts/generate_contracts.py
from __future__ import annotations

from datetime import datetime
from typing import Any, Literal
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field


class ContractModel(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

class LogBatchEntriesItem(ContractModel):
    t: datetime = Field(...)
    lvl: Literal['debug', 'info', 'warn', 'warning', 'error'] = Field(...)
    msg: str = Field(...)

class TestResultStagesItem(ContractModel):
    name: str = Field(...)
    outcome: Literal['passed', 'failed', 'aborted'] = Field(...)
    started_at: datetime = Field(alias="startedAt")
    finished_at: datetime = Field(alias="finishedAt")

class Heartbeat(ContractModel):
    ts: datetime = Field(...)
    status: Literal['idle', 'running', 'error'] = Field(...)
    current_run_id: UUID | None = Field(default=None, alias="currentRunId")

class LogBatch(ContractModel):
    ts: datetime = Field(...)
    run_id: UUID | None = Field(default=None, alias="runId")
    entries: list[LogBatchEntriesItem] = Field(...)

class TestResult(ContractModel):
    ts: datetime = Field(...)
    run_id: UUID | None = Field(default=None, alias="runId")
    dut_id: str = Field(alias="dutId")
    outcome: Literal['passed', 'failed', 'aborted'] = Field(...)
    config_revision: int | None = Field(default=None, alias="configRevision")
    started_at: datetime = Field(alias="startedAt")
    finished_at: datetime = Field(alias="finishedAt")
    stages: list[TestResultStagesItem] | None = Field(default=None, alias="stages")

class Stage(ContractModel):
    ts: datetime = Field(...)
    run_id: UUID | None = Field(default=None, alias="runId")
    index: int = Field(...)
    name: str = Field(...)
    status: Literal['pending', 'running', 'passed', 'failed', 'aborted', 'error'] = Field(...)

class Command(ContractModel):
    id: UUID = Field(...)
    kind: Literal['run-plan', 'abort-run', 'reboot'] = Field(...)
    payload: dict[str, Any] | None = Field(default=None, alias="payload")
