# generated by proto/scripts/generate_contracts.py
from __future__ import annotations

from datetime import datetime
from typing import Literal
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field


class ContractModel(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

class Station(ContractModel):
    id: UUID = Field(...)
    org_id: UUID = Field(alias="orgId")
    name: str = Field(...)
    status: Literal['offline', 'idle', 'running', 'error'] = Field(...)
    last_seen_at: datetime | None = Field(default=None, alias="lastSeenAt")

class RegisterStationRequest(ContractModel):
    name: str = Field(...)
