#!/usr/bin/env python
from __future__ import annotations

import argparse
import keyword
import re
from pathlib import Path
from typing import Any

import yaml


CS_HEADER = """// <auto-generated />
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

"""

def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("language", choices=("csharp", "python"))
    parser.add_argument("--spec", choices=("openapi", "asyncapi"), required=True)
    parser.add_argument("--input", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()

    document = yaml.safe_load(args.input.read_text(encoding="utf-8"))
    schemas = document["components"]["schemas"]
    graph = SchemaGraph(schemas)

    if args.language == "csharp":
        text = CSharpGenerator(args.spec, graph).generate()
    else:
        text = PythonGenerator(graph).generate()

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(text, encoding="utf-8")


class SchemaGraph:
    def __init__(self, schemas: dict[str, Any]) -> None:
        self._schemas = schemas
        self.inline_objects: dict[str, dict[str, Any]] = {}

    @property
    def names(self) -> list[str]:
        return list(self._schemas)

    def schema(self, name: str) -> dict[str, Any]:
        return self._schemas[name]

    def resolve_ref_name(self, ref: str) -> str:
        prefix = "#/components/schemas/"
        if not ref.startswith(prefix):
            raise ValueError(f"Unsupported reference: {ref}")
        return ref.removeprefix(prefix)

    def collect_inline_objects(self) -> None:
        for name in self.names:
            self._collect_inline_objects(name, self.schema(name))

    def _collect_inline_objects(self, owner: str, schema: dict[str, Any]) -> None:
        for prop_name, prop_schema in schema.get("properties", {}).items():
            if prop_schema.get("type") != "array":
                continue

            item_schema = prop_schema.get("items", {})
            if item_schema.get("type") != "object" or "$ref" in item_schema:
                continue

            item_name = f"{owner}{pascal_case(prop_name)}Item"
            self.inline_objects[item_name] = item_schema


class CSharpGenerator:
    def __init__(self, spec: str, graph: SchemaGraph) -> None:
        self._spec = spec
        self._graph = graph
        self._graph.collect_inline_objects()

    def generate(self) -> str:
        namespace = "Rest" if self._spec == "openapi" else "Mqtt"
        lines = [CS_HEADER, f"namespace Embeint.Htf.Contracts.{namespace};", ""]

        for name in [*self._graph.names, *self._graph.inline_objects]:
            schema = self._graph.inline_objects.get(name, self._graph.schema(name) if name in self._graph.names else {})
            lines.extend(self._definition(name, schema))
            lines.append("")

        return "\n".join(lines).rstrip() + "\n"

    def _definition(self, name: str, schema: dict[str, Any]) -> list[str]:
        if schema.get("enum"):
            return self._enum(name, schema)

        required = set(schema.get("required", []))
        lines = [f"public sealed record {pascal_case(name)}", "{"]
        for prop_name, prop_schema in schema.get("properties", {}).items():
            prop_type = self._type(prop_schema, f"{name}{pascal_case(prop_name)}Item")
            prop_required = prop_name in required
            nullable = self._is_nullable(prop_schema) or not prop_required
            cs_type = f"{prop_type}?" if nullable and not prop_type.endswith("?") else prop_type
            cs_name = pascal_case(prop_name)

            lines.append(f"    [JsonPropertyName(\"{prop_name}\")]")
            if prop_required and not nullable:
                lines.append(f"    public required {cs_type} {cs_name} {{ get; init; }}")
            else:
                lines.append(f"    public {cs_type} {cs_name} {{ get; init; }} = null;")
            lines.append("")

        if lines[-1] == "":
            lines.pop()
        lines.append("}")
        return lines

    @staticmethod
    def _enum(name: str, schema: dict[str, Any]) -> list[str]:
        values = schema["enum"]
        if not all(isinstance(value, str) for value in values):
            raise ValueError(f"C# generation only supports string enums: {name}")
        lines = [
            f"[JsonConverter(typeof(JsonStringEnumConverter<{pascal_case(name)}>))]",
            f"public enum {pascal_case(name)}",
            "{",
        ]
        for value in values:
            lines.extend([
                f"    [JsonStringEnumMemberName(\"{value}\")]",
                f"    {pascal_case(value)},",
            ])
        lines.append("}")
        return lines

    def _type(self, schema: dict[str, Any], inline_name: str) -> str:
        if len(schema.get("allOf", [])) == 1:
            return self._type(schema["allOf"][0], inline_name)
        if "$ref" in schema:
            return pascal_case(self._graph.resolve_ref_name(schema["$ref"]))

        schema_type = schema.get("type")
        fmt = schema.get("format")
        if schema_type == "string" and fmt == "uuid":
            return "Guid"
        if schema_type == "string" and fmt == "date-time":
            return "DateTimeOffset"
        if schema_type == "string":
            return "string"
        if schema_type == "integer" and fmt == "int64":
            return "long"
        if schema_type == "integer":
            return "int"
        if schema_type == "number":
            return "double"
        if schema_type == "boolean":
            return "bool"
        if schema_type == "array":
            return f"IReadOnlyList<{self._type(schema['items'], inline_name)}>"
        if schema_type == "object" and isinstance(schema.get("additionalProperties"), dict):
            return f"IReadOnlyDictionary<string, {self._type(schema['additionalProperties'], inline_name)}>"
        if schema_type == "object" and schema.get("additionalProperties"):
            return "IReadOnlyDictionary<string, object?>"
        if schema_type == "object":
            return pascal_case(inline_name)
        return "object"

    @staticmethod
    def _is_nullable(schema: dict[str, Any]) -> bool:
        return bool(schema.get("nullable"))


class PythonGenerator:
    def __init__(self, graph: SchemaGraph) -> None:
        self._graph = graph
        self._graph.collect_inline_objects()
        self._typing_imports: set[str] = set()
        self._needs_datetime = False
        self._needs_uuid = False

    def generate(self) -> str:
        body: list[str] = []
        for name in [*self._graph.inline_objects, *self._graph.names]:
            schema = self._graph.inline_objects.get(name, self._graph.schema(name) if name in self._graph.names else {})
            body.extend(self._definition(name, schema))
            body.append("")

        return "\n".join([*self._header(), *body]).rstrip() + "\n"

    def _header(self) -> list[str]:
        lines = [
            "# generated by proto/scripts/generate_contracts.py",
            "from __future__ import annotations",
            "",
        ]

        if self._needs_datetime:
            lines.extend(["from datetime import datetime"])
        if self._typing_imports:
            lines.extend([f"from typing import {', '.join(sorted(self._typing_imports))}"])
        if self._needs_uuid:
            lines.extend(["from uuid import UUID"])

        lines.extend([
            "",
            "from pydantic import BaseModel, ConfigDict, Field",
            "",
            "",
            "class ContractModel(BaseModel):",
            "    model_config = ConfigDict(populate_by_name=True)",
            "",
        ])
        return lines

    def _definition(self, name: str, schema: dict[str, Any]) -> list[str]:
        enum = schema.get("enum")
        if enum:
            self._typing_imports.add("Literal")
            return [f"{pascal_case(name)} = Literal[{', '.join(repr(item) for item in enum)}]"]

        required = set(schema.get("required", []))
        lines = [f"class {pascal_case(name)}(ContractModel):"]
        properties = schema.get("properties", {})
        if not properties:
            lines.append("    pass")
            return lines

        for prop_name, prop_schema in properties.items():
            field_name = python_name(prop_name)
            field_type = self._type(prop_schema, f"{name}{pascal_case(prop_name)}Item")
            if self._is_nullable(prop_schema) or prop_name not in required:
                field_type = f"{field_type} | None"

            default = "" if prop_name in required else "default=None, "
            alias = f"Field({default}alias=\"{prop_name}\")" if field_name != prop_name or default else "Field(...)"
            lines.append(f"    {field_name}: {field_type} = {alias}")

        return lines

    def _type(self, schema: dict[str, Any], inline_name: str) -> str:
        if len(schema.get("allOf", [])) == 1:
            return self._type(schema["allOf"][0], inline_name)
        if "$ref" in schema:
            return pascal_case(self._graph.resolve_ref_name(schema["$ref"]))

        enum = schema.get("enum")
        if enum:
            self._typing_imports.add("Literal")
            return "Literal[" + ", ".join(repr(item) for item in enum) + "]"

        schema_type = schema.get("type")
        fmt = schema.get("format")
        if schema_type == "string" and fmt == "uuid":
            self._needs_uuid = True
            return "UUID"
        if schema_type == "string" and fmt == "date-time":
            self._needs_datetime = True
            return "datetime"
        if schema_type == "string":
            return "str"
        if schema_type == "integer":
            return "int"
        if schema_type == "number":
            return "float"
        if schema_type == "boolean":
            return "bool"
        if schema_type == "array":
            return f"list[{self._type(schema['items'], inline_name)}]"
        if schema_type == "object" and isinstance(schema.get("additionalProperties"), dict):
            return f"dict[str, {self._type(schema['additionalProperties'], inline_name)}]"
        if schema_type == "object" and schema.get("additionalProperties"):
            self._typing_imports.add("Any")
            return "dict[str, Any]"
        if schema_type == "object":
            return pascal_case(inline_name)
        self._typing_imports.add("Any")
        return "Any"

    @staticmethod
    def _is_nullable(schema: dict[str, Any]) -> bool:
        return bool(schema.get("nullable"))


def pascal_case(value: str) -> str:
    parts = re.split(r"[^A-Za-z0-9]+", value)
    result = "".join(_capitalize_camel_part(part) for part in parts if part)
    return result or "Generated"


def _capitalize_camel_part(value: str) -> str:
    subparts = re.findall(r"[A-Z]+(?=[A-Z][a-z]|\d|$)|[A-Z]?[a-z]+|\d+", value)
    return "".join(part[:1].upper() + part[1:] for part in subparts) if subparts else value.capitalize()


def python_name(value: str) -> str:
    name = re.sub(r"(?<!^)(?=[A-Z])", "_", value).replace("-", "_").lower()
    if keyword.iskeyword(name):
        return f"{name}_"
    return name


if __name__ == "__main__":
    main()
