station:
  org_id: ${HTF_ORG_ID}
  station_id: ${HTF_STATION_ID}

plugins:
  - infuse

programmers:
  - name: jlink_1
    kind: jlink
    serial_number: 823000667
    target_device: nrf54l15_m33
    board: kudu
    rtt_channel: 0
    rtt_telnet_port: 19021

stages:
  - name: Device Erase Inital
    kind: nrfutil_device_recover
    programmer: jlink_1
  - name: Flash Validation Firmware
    kind: firmware_flash
    programmer: jlink_1
    firmware_id: 9a720fc7-1ce5-414d-ab99-b7b4fecea319
    firmware_version: latest
    path: zephyr/zephyr.hex
  - name: Validation
    kind: infuse_validation_rtt
    programmer: jlink_1
    reset_before_capture: true
    number_of_tests: 10
    test_timeout_seconds: 60
    tests: [BT, MODEM, DISK, FLASH, LED, IMU]
  - name: Device Erase Production
    kind: nrfutil_device_recover
    programmer: jlink_1
  - name: Get Hardware ID
    kind: hardware_id
    programmer: jlink_1
  - name: Device Provisioning
    kind: infuse_provisioning
    programmer: jlink_1
    board_pool: kudu
    uicr:
      - name: infuse_id
        bytes: 8
        value: infuse_id
        endian: LSB
  - name: Flash Release Firmware
    kind: firmware_flash
    programmer: jlink_1
    firmware_id: fb7558d3-66c9-452a-bae9-7356395d6cbd
    firmware_version: latest
    path: zephyr/zephyr.hex
