name: Publish package

on:
  release:
    types: [published]

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    runs-on: [self-hosted, linux, proxmox-htf-station]
    environment:
      name: pypi
      url: https://pypi.org/p/embeint-htf-station
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v7
      - uses: actions/setup-python@v6
        with:
          python-version: "3.14"
      - run: uv build
      - uses: pypa/gh-action-pypi-publish@release/v1
